# render.yaml

previews:
  generation: manual
  expireAfterDays: 7

envVarGroups:
  - name: APP-SECRETS-DEV
  - name: APP-SECRETS-PROD

services:
  - name: api-dev
    type: web
    runtime: node
    repo: https://github.com/jtaiwo09/Fola-Store
    branch: dev
    rootDir: backend # tells Render where the actual app code is
    plan: standard
    buildCommand: npm install
    startCommand: node index.js # or npm start or your entry point
    envVars:
      - fromGroup: APP-SECRETS-DEV
    autoDeploy: true

  - name: api-production
    type: web
    runtime: node
    repo: https://github.com/jtaiwo09/Fola-Store
    branch: main
    rootDir: backend
    plan: standard
    buildCommand: npm install
    startCommand: node index.js # or npm start or your entry point
    envVars:
      - fromGroup: APP-SECRETS-PROD
    autoDeploy: true
