# render.yaml

# optional: preview settings (for PR preview environments)
previews:
  generation: manual # or automatic if you want PR previews
  expireAfterDays: 7

envVarGroups:
  - name: APP-SECRETS-DEV
  - name: APP-SECRETS-PROD

services:
  - name: api-dev
    type: web
    repo: https://github.com/jtaiwo09/Fola-Store/tree/dev/backend
    branch: dev # or staging branch
    plan: standard
    envVars:
      # you can define env vars, or reference the group
      - fromGroup: APP-SECRETS-DEV
    # You might disable auto-deploy for this or enable:
    autoDeployTrigger: commit

  - name: api-production
    type: web
    repo: https://github.com/jtaiwo09/Fola-Store/tree/main/backend
    branch: main # or your release branch
    plan: standard
    envVars:
      - fromGroup: APP-SECRETS-PROD
    autoDeployTrigger: commit # Or you may disable this and deploy manually
